Repository ArcadeAI/docs, pull requests merged in 2025-08, with the labels that each got.

#390 MS Teams toolkit docs
  pages/toolkits/social-communication/microsoft_teams.mdx
  pages/toolkits/social-communication/microsoft_teams/reference.mdx
  pages/toolkits/social-communication/teams/reference.mdx
  public/examples/integrations/toolkits/microsoft_teams/create_chat_example_call_tool.js
  public/examples/integrations/toolkits/microsoft_teams/create_chat_example_call_tool.py
  public/examples/integrations/toolkits/microsoft_teams/get_channel_message_replies_example_call_tool.js
  public/examples/integrations/toolkits/microsoft_teams/get_channel_message_replies_example_call_tool.py
  public/examples/integrations/toolkits/microsoft_teams/get_channel_messages_example_call_tool.js
  public/examples/integrations/toolkits/microsoft_teams/get_channel_messages_example_call_tool.py
  public/examples/integrations/toolkits/microsoft_teams/get_channel_metadata_example_call_tool.js
  public/examples/integrations/toolkits/microsoft_teams/get_channel_metadata_example_call_tool.py
  public/examples/integrations/toolkits/microsoft_teams/get_chat_message_by_id_example_call_tool.js
  public/examples/integrations/toolkits/microsoft_teams/get_chat_message_by_id_example_call_tool.py
  public/examples/integrations/toolkits/microsoft_teams/get_chat_messages_example_call_tool.js
  public/examples/integrations/toolkits/microsoft_teams/get_chat_messages_example_call_tool.py
  public/examples/integrations/toolkits/microsoft_teams/get_chat_metadata_example_call_tool.js
  public/examples/integrations/toolkits/microsoft_teams/get_chat_metadata_example_call_tool.py
  public/examples/integrations/toolkits/microsoft_teams/get_signed_in_user_example_call_tool.js
  public/examples/integrations/toolkits/microsoft_teams/get_signed_in_user_example_call_tool.py
  public/examples/integrations/toolkits/microsoft_teams/get_team_example_call_tool.js
  public/examples/integrations/toolkits/microsoft_teams/get_team_example_call_tool.py
  public/examples/integrations/toolkits/microsoft_teams/list_channels_example_call_tool.js
  public/examples/integrations/toolkits/microsoft_teams/list_channels_example_call_tool.py
  public/examples/integrations/toolkits/microsoft_teams/list_chats_example_call_tool.js
  public/examples/integrations/toolkits/microsoft_teams/list_chats_example_call_tool.py
  public/examples/integrations/toolkits/microsoft_teams/list_team_members_example_call_tool.js
  public/examples/integrations/toolkits/microsoft_teams/list_team_members_example_call_tool.py
  public/examples/integrations/toolkits/microsoft_teams/list_teams_example_call_tool.js
  public/examples/integrations/toolkits/microsoft_teams/list_teams_example_call_tool.py
  public/examples/integrations/toolkits/microsoft_teams/list_users_example_call_tool.js
  public/examples/integrations/toolkits/microsoft_teams/list_users_example_call_tool.py
  public/examples/integrations/toolkits/microsoft_teams/reply_to_channel_message_example_call_tool.js
  public/examples/integrations/toolkits/microsoft_teams/reply_to_channel_message_example_call_tool.py
  public/examples/integrations/toolkits/microsoft_teams/reply_to_chat_message_example_call_tool.js
  public/examples/integrations/toolkits/microsoft_teams/reply_to_chat_message_example_call_tool.py
  public/examples/integrations/toolkits/microsoft_teams/search_channels_example_call_tool.js
  public/examples/integrations/toolkits/microsoft_teams/search_channels_example_call_tool.py
  public/examples/integrations/toolkits/microsoft_teams/search_messages_example_call_tool.js
  public/examples/integrations/toolkits/microsoft_teams/search_messages_example_call_tool.py
  public/examples/integrations/toolkits/microsoft_teams/search_people_example_call_tool.js
  public/examples/integrations/toolkits/microsoft_teams/search_people_example_call_tool.py
  public/examples/integrations/toolkits/microsoft_teams/search_team_members_example_call_tool.js
  public/examples/integrations/toolkits/microsoft_teams/search_team_members_example_call_tool.py
  public/examples/integrations/toolkits/microsoft_teams/search_teams_example_call_tool.js
  public/examples/integrations/toolkits/microsoft_teams/search_teams_example_call_tool.py
  public/examples/integrations/toolkits/microsoft_teams/search_users_example_call_tool.js
  public/examples/integrations/toolkits/microsoft_teams/search_users_example_call_tool.py
  public/examples/integrations/toolkits/microsoft_teams/send_message_to_channel_example_call_tool.js
  public/examples/integrations/toolkits/microsoft_teams/send_message_to_channel_example_call_tool.py
  public/examples/integrations/toolkits/microsoft_teams/send_message_to_chat_example_call_tool.js
  public/examples/integrations/toolkits/microsoft_teams/send_message_to_chat_example_call_tool.py
Labels: documentation

#399 Fix broken links
  pages/toolkits/social-communication/microsoft_teams.mdx
  public/images/icons/ms_teams.png
  src/components/custom/Toolkits/toolkits-config.ts
Labels: bug, documentation

#409 Document Microsoft scopes required by Arcade toolkits
  pages/home/auth-providers/microsoft.mdx
Labels: documentation, enhancement
